In [1]:
import numpy as np

In [8]:
array_1 = np.array([1,2,3,4,5])

#size represents number of elements in array
print(array_1.size)

#ndim represents that its a 1 dimensional, 2 dimensional or 3 dimensional array
print(array_1.ndim)

#dtype represents the data type of elements stored in array
print(array_1.dtype)

#type represents the variable type in python like it shows below that its a numpy array
type(array_1)

#shape represents the number of rows and columns in a array
array_1.shape


5
1
int32


(5,)

In [11]:
#Like wise two dimensional array 
array_2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(array_2d)

#And three dimensional array

array_3d = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],[4,5,6],[7,8,9],[1,2,3]])

print(array_3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9])]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
