# Numpy array slicing

In [1]:
import numpy as np

In [3]:
array_2d = np.arange(0,100).reshape(10,10)
print(array_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [11]:
#printing 67
print(array_2d[6,7])

#slicing 2nd row only
print(array_2d[1])

#slicing 4th column
print(array_2d[:,3])

#slicing 3rd,4th,5th row

print(array_2d[2:5,])

#slicing first three columns and 4 rows
print(array_2d[:4,:3])

67
[10 11 12 13 14 15 16 17 18 19]
[ 3 13 23 33 43 53 63 73 83 93]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# checking matrix or array type

In [15]:
print(array_2d.dtype)
#means each value is stored in 32 bits or 4 bytes
print(array_2d.itemsize)

int32
4


# Cocatenation or spilting of numpy array

In [19]:
# Concatenating two array using concatenate function and vstack, hstack
arr_1 = np.arange(10,19).reshape(3,3)
arr_2 = np.arange(20,29).reshape(3,3)

print(arr_1)
print(arr_2)


[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [22]:
#concatenation along column using concatenate function
np.concatenate((arr_1,arr_2), axis = 0)
#concatenation along rows
np.concatenate((arr_1,arr_2), axis = 1)

array([[10, 11, 12, 20, 21, 22],
       [13, 14, 15, 23, 24, 25],
       [16, 17, 18, 26, 27, 28]])

In [25]:
#Now using vstack(vertical stack), hstack(horizontal stack)
print(np.vstack((arr_1,arr_2)))

#Horizontal Stack

print(np.hstack((arr_1,arr_2)))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [20 21 22]
 [23 24 25]
 [26 27 28]]
[[10 11 12 20 21 22]
 [13 14 15 23 24 25]
 [16 17 18 26 27 28]]


# Now spliting Numpy array

In [29]:
arr_3 = np.arange(1,21).reshape(4,5)
print(arr_3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [38]:
#Remember split returns python list and with in list each element is of array type
list_1 = np.split(arr_3, 2, axis = 0)
print(list_1)
print(type(list_1))
print(list_1[1])
print(type(list_1[0]))


[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
<class 'list'>
[[11 12 13 14 15]
 [16 17 18 19 20]]
<class 'numpy.ndarray'>


In [48]:
#Now issue is that we cannot split columns into equal parts so 
print(arr_3)
np.split(arr_3,[1,3],axis=1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20]])]